## Binomial Distribution----
# rbinom()----
# rbinom(sample_size=10, n= number of simulated experiments, prob=0.5)

# The number of successes in each of 20 simulated experiments
# is being generated by discrete random var Y with probability 
# distribution p(y|theta) called the binomial distribution

# Random numbers from the binomial distribution
# Used to generate the number of success of independent trials. 


args(rbinom)
# generate the number of successes of independent trials: 

# n = number of experiments 
# size = no of trials in each experiment 
# prob = the probability that each trial is a success
# the output is vector length n, so essentially, for each replicator, 
# the number of successful trials is calculated and reported.

# Example: 
# Unbiased coin 100 times in a row
# counting how many times the coin lands on heads
# 7 experiments  

rbinom(n = 7, size = 100, prob = 0.5)

# Returns the number of success out of each experiment of 100  tosses.
hist(rbinom(n = 7, size = 100, prob = 0.5))
barplot(rbinom(n = 7, size = 100, prob = 0.5))
args(barplot)

rbinom(n=20, size = 10, prob = 0.5)
barplot(rbinom(n=20, size = 10, prob = 0.5))
?rbinom

rbinom()
p1 <- rbinom(n=20, size=10, prob = 0.5)
hist(p1)
p1


## Compute the probability of a discete outcome----  
# dbinom()----  

# 1. What is the p of 5 successes out of 10 trials (sample size) when theta = 0.5
dbinom(5, size = 10, prob = 0.5) 

# 2. Wht is the p of success for theta = 0.1 or 0.9  
dbinom(5, size = 10, prob = c(0.1, 0.9))  

# Note, this is for discrete values.  The p of a continuous value would always be zero.

## dbinom() -- Cumulative probability with dbinom----
## Compute the cumulative prob of obtaining 1 or less, 2 or less.  

#  This  is a simple sum procedure:
dbinom(0, size = 10, prob = 0.5) + dbinom(2, size = 10, prob = 0.5) + dbinom(0, size = 10, prob = 0.5)

dbinom(0:2, size = 10, prob = 0.5)

## pbinom()---- 

# The probability of 2 or less successes:  
pbinom(2, size = 10, prob = 0.5, lower.tail = TRUE)

# For probability of 2 or more successes, set lower.tail=FALSE
pbinom(2, size = 10, prob = 0.5, lower.tail = FALSE)

## qbinom() quantile function----
## qbinom() = Inverse Cumulative Density Function, for Binomial Distribution CDF----

# Returns the quantile, the value of k (successes) with a given probability.
# What is the value k when the probability
# of obtaining k or less success is 0.37  

qbinom(0.37, size=10, 0.5)

# The PMF probability mass function p(y|theta) is the probability distribution.

# The PMF defines the probability of each outcome. 

## Quantiles----  
# Reference:  Ed Boone Bayesian intervals and the Bernouille Trial

# alpa = 12 successes  out of 100.  Beta Failures = 88
# 28 out of 387 have an intention to buy.
# sum of xi  28 said yes.
# To calculate using priors 
# alpha = 12+28, beta = 88+ 387-28

# CALCULATE THE 95% Credible Interval

# xi = successes
# p|D ~ Beta(12,28, 88+387 - 28) = Beta(40, 447) 
# Prior p~ Beta(alpha, beta)
# Posterior p|D ~ Beta(alpha + sum xi, beta + n(sum xi))
# Mean = alpha/(alpha + beta)
# Variance = (alpha)(beta)/(alpha+beta)^2 (alpha+beta+1)

## THE CREDIBLE INTERVAL USING "qbeta()"   
## Use 0.5 as a point estimate for median  
qbeta(c(0.025, 0.5, 0.975), 40, 447)

# use pbeta() to get probabilies out of the posterior distribution

## Uniform Distribtion----
# each number has an equal probability
# n = number of trials
runif(n=15, min=1, max = 10)

runif(n=15, min=1, max=10)
runif(3, 0, 1)
runif(3) 
hist(runif(3))

## Normal Distribution----
args(rnorm)
rnorm(20)
rnorm(10, mean=50, sd=100)
hist(rnorm(n=10, mean = 50, sd = 100))
